<!-- META SNIPPET -->

<xmlnuke-mobilebody_basics />
<xmlnuke-mobilebody_editform />
<!--
<!xmlnuke-mobilebody_editlist />
<!xmlnuke-mobilebody_calendar />
<!xmlnuke-mobilebody_faq />
<!xmlnuke-mobilebody_duallist />
<!xmlnuke-mobilebody_tabview />
<!xmlnuke-mobilebody_sortablelist />
<!xmlnuke-mobilebody_poll />
<!xmlnuke-mobilebody_treeview />
<!xmlnuke-mobilebody_uialert />
<!xmlnuke-mobilebody_mediagallery />
-->