#!/bin/sh

echo XMLNuke PHP5 Project Creator
echo By JG @ 2009
echo

if [ -z "$1" -o -z "$2" -o -z "$3" ]
then
	echo Use this script to create a XMLNuke PHP5 project ready to use on PDT Eclipse or another editor.
	echo
	echo Usage:
	echo "   create-php5-project.sh PATHTOYOURPROJECT sitename language1 language2... "
	echo
	echo Where:
	echo "   PATHTOYOURPROJECT is the full path for your project "
	echo "   sitename is your site, for example: mysite "
	echo "   language is the main language for your project. e.g.: pt-br or en-us or de-de "
	echo
else
	HOME="$1"
	SITE="$2"

	if [ -d "$PWD/xmlnuke-php5" ]
	then
		if [ -d "$HOME" ]
		then

			ln -sf "$PWD/xmlnuke-php5/imagevalidate.php" "$HOME/"
			ln -sf "$PWD/xmlnuke-php5/xmlnukeadmin.php" "$HOME/"
			ln -sf "$PWD/xmlnuke-php5/xmlnuke.inc.php" "$HOME/"
			ln -sf "$PWD/xmlnuke-php5/check_install.php.rename_to_work" "$HOME/check_install.php"
			ln -sf "$PWD/xmlnuke-php5/index.php.rename_to_work" "$HOME/index.php"
			ln -sf "$PWD/xmlnuke-php5/xmlnuke.php" "$HOME/"

			ln -sf "$PWD/xmlnuke-php5/writepage.inc.php.rename_to_work" "$HOME/writepage.inc.php"
			ln -sf "$PWD/xmlnuke-php5/unittest.php" "$HOME/"
			ln -sf "$PWD/xmlnuke-php5/webservice.php" "$HOME/"
			ln -sf "$PWD/xmlnuke-php5/chart.php" "$HOME/"
			
			
			touch "$HOME/config.inc.php"
			chmod 777 "$HOME/config.inc.php"
			mkdir -p "$HOME/static"
			mkdir -p "$HOME/data/anydataset"
			mkdir -p "$HOME/data/cache"
			mkdir -p "$HOME/data/lang"
			mkdir -p "$HOME/data/offline"
			mkdir -p "$HOME/data/xml"
			mkdir -p "$HOME/data/xsl"
			mkdir -p "$HOME/data/snippet"
			
			while [ ! -z "$3" ]
			do
				mkdir -p "$HOME/data/xml/$3"
				cp "$PWD/xmlnuke-data/sites/index.xsl.template" "$HOME/data/xsl/index.$3.xsl"
				cp "$PWD/xmlnuke-data/sites/page.xsl.template" "$HOME/data/xsl/page.$3.xsl"
				cp "$PWD/xmlnuke-data/sites/index.xml.template" "$HOME/data/xml/$3/index.$3.xml"
				cp "$PWD/xmlnuke-data/sites/home.xml.template" "$HOME/data/xml/$3/home.$3.xml"
				cp "$PWD/xmlnuke-data/sites/notfound.xml.template" "$HOME/data/xml/$3/notfound.$3.xml"
				echo "xmlnuke\n+home.$3.xml" > "$HOME/data/xml/$3/index.php.btree"
				shift
			done

			chmod 777 -R "$HOME/data"
			mkdir -p "$HOME/lib/modules"
			cp "$PWD/xmlnuke-data/sites/module.php.template" "$HOME/lib/modules/home.class.php"

			echo "<?php" > "$HOME/config.default.php"
			echo "# This file was generated by create-php5-project.sh. " >> "$HOME/config.default.php"
			echo "# You can safely remove this file after you XMLNuke installation is running." >> "$HOME/config.default.php"
			echo "\$configValues[\"xmlnuke.ROOTDIR\"]='$PWD/xmlnuke-data'; " >> "$HOME/config.default.php"
			echo "\$configValues[\"xmlnuke.USEABSOLUTEPATHSROOTDIR\"] = true; " >> "$HOME/config.default.php"
			echo "\$configValues[\"xmlnuke.DEFAULTSITE\"]='$SITE'; " >> "$HOME/config.default.php"
			echo "\$configValues[\"xmlnuke.EXTERNALSITEDIR\"] = '$SITE=$HOME/data'; " >> "$HOME/config.default.php"
			echo "\$configValues[\"xmlnuke.PHPLIBDIR\"] = 'mylib=$HOME/lib'; " >> "$HOME/config.default.php"
			echo "\$configValues[\"xmlnuke.PHPXMLNUKEDIR\"] = '$PWD/xmlnuke-php5'; " >> "$HOME/config.default.php"
			echo "?>" >> "$HOME/config.default.php"
		

			echo Done.
			echo
			echo You must do some configurations manualy:
			echo "  - Create an alias \"/common\" pointing to \"$PWD/xmlnuke-common\" "
			echo "  - Point the document root on your Web Server to \"$HOME\" "
			echo
			echo After this you can play with these URLs:
			echo http://localhost/xmlnuke.php?xml=home
			echo http://localhost/xmlnuke.php?module=mylib.home
			echo

		else
			echo "'$HOME' does not exists. Create it first."
		fi
	else
		echo XMLNuke release not found!!! Cannot continue.
	fi
fi
